# Generated by Django 5.0.8 on 2024-08-06 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
