# Generated by Django 5.0.8 on 2024-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.AddField(
            model_name='usuario',
            name='CAEC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='CALC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='CH2O',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='FAF',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='FAVC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='FCVC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='MTrans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='NCP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='NObeyesdad',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='SCC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='SMOKE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='TUE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='family_history',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=0),
        ),
    ]
