# Generated by Django 5.0.8 on 2024-08-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0003_remove_usuario_nome_usuario_caec_usuario_calc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
