# Generated by Django 5.0.8 on 2024-08-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0004_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(default=0),
        ),
    ]
